### ISSUE TITLE
One ant version to rule them all

### ISSUE THREAD

**Issue by elharo** [gwtproject/tools#5]
Please tell me we don't actually need three different version of ant:

https://github.com/gwtproject/tools/tree/master/lib/apache

Can two of these be deleted?

**Comment by tbroyer** [comment]
The (original) idea is that the latest version of `tools` can be used to build any version of GWT; i.e. to build, e.g. GWT 2.1, you don't need to checkout a “corresponding” commit of `tools`. That also means that on a continuous integration environment, you only have to keep `tools` up-to-date and you can build any branch, even if they start diverging wrt dependencies (e.g. branching for a release, and the trunk switching to newer libraries).

Also, given how Git works, deleting old JARs wouldn't trim down the size of the repo, so removing old libs would really only be a “cosmetic” change.

**Comment by Bob131** [comment]
> deleting old JARs wouldn't trim down the size of the repo

Perhaps.

> so removing old libs would really only be a “cosmetic” change.

Not so, see https://www.git-scm.com/docs/git-clone#git-clone---depthltdepthgt
